version: '3.8'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./nginx/npm_data:/data
      - ./nginx/npm_letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: botbodinho
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped
