name: Deploy to Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Home Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          script: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.HOME_SERVER_PORT }} ${{ secrets.HOME_SERVER_USER }}@${{ secrets.HOME_SERVER_HOST }} << 'EOF'
            cd ~/bot-bodinho/
            git pull origin main
            yarnpkg
            yarnpkg start
