name: Deploy to Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Home Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOME_SERVER_HOST }}
          username: ${{ secrets.HOME_SERVER_USER }}
          password: ${{ secrets.HOME_SERVER_PASSWORD }}
          port: ${{ secrets.HOME_SERVER_PORT }}
          script: |
            cd /caminho/do/projeto
            git pull origin main
            yarn build
            yarn start
