name: Deploy to Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Home Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOME_SERVER_HOST }} # IP ou nome do servidor
          username: ${{ secrets.HOME_SERVER_USER }} # Nome de usuário
          password: ${{ secrets.HOME_SERVER_PASSWORD }} # Senha do usuário
          port: ${{ secrets.HOME_SERVER_PORT }} # Porta SSH, normalmente 22
          script: |
            cd ~/bot-bodinho/
            git pull origin main
            yarnpkg
            yarnpkg start
